### ISSUE TITLE
How can I set passphrase for APNS?

### ISSUE THREAD

**Issue by khaihkd** [dgilland/pushjack#13]
My certificate has passphrase. How can I set it?

**Comment by dgilland** [comment]
That isn't currently supported. PRs welcome though :smile:!

**Comment by khaihkd** [comment]
do you have some solutions?

**Comment by dgilland** [comment]
You may want to check out a different APNS client library:

- https://bitbucket.org/sardarnl/apns-client/overview
- https://bitbucket.org/sardarnl/apns-client/src/48f7115722e0fdcc12cd6f7263b55fd1f40409b2/apnsclient/certificate.py?at=default&fileviewer=file-view-default#certificate.py-26

They have support for loading certificates with passphrases.

**Comment by dgilland** [comment]
Otherwise, you could try subclassing pushjack.apns.APNSConnection and overriding `APNSConnection.connect` (maybe borrow from `create_socket`) to support reading a certificate file with a passphrase:

- https://github.com/dgilland/pushjack/blob/master/pushjack/apns.py#L275
- https://github.com/dgilland/pushjack/blob/master/pushjack/apns.py#L693
