### ISSUE TITLE
Support for GCM notification payload

### ISSUE THREAD

**Issue by Jean-Daniel** [dgilland/pushjack#14]
GCM let the sender provide a `notification` payload that can be displayed without having to wake-up the target application.

See https://developers.google.com/cloud-messaging/concept-options#notifications_and_data_messages

actually, pushjack does not provide a way to build such message.

**Comment by dgilland** [comment]
I don't have much free time to work on this, but PRs are welcome.

The main message class for GCM is here: https://github.com/dgilland/pushjack/blob/master/pushjack/gcm.py#L145

A quick way to support the `notification` field would be to require `message` be a `dict` with a `notification` key that would be hoisted up to the top level while the rest of the `message` dict is dropped under `data` (the current behavior).

```python
notification = {'title': 'Title', 'body': 'Body', 'icon': 'icon'}
alert = {'notification': notification, 'message': 'My Message'}
gcm.send(ids, alert)
```

A supplemental option would be to add `notification` as a keyword argument and require it to be a `dict`.

```python
notification = {'title': 'Title', 'body': 'Body', 'icon': 'icon'}
gcm.send(ids, 'My Message', notification=notification)
```

Still another option would be to call out each of the `notification` subkeys as keyword arguments like `notification_title`, `notification_body`, and `notification_icon`.

```python
gcm.send(ids, 
         'My Message',
         notification_title='Title',
         notification_body='Body',
         notification_icon='Icon')
```

And since messages can now have a `notification` without `data`, the `message` argument should be allowed to be `None` and not included.

```python
gcm.send(ids, notification=notification)
```

**Comment by dgilland** [comment]
I've release [v1.1.0](https://pypi.python.org/pypi/pushjack/1.1.0) with support for `notification` payloads.

I implemented the first two styles (mentioned in my previous comment) for passing a notification in:

```python
# Style 1: Notification as part of alert dict
notification = {'title': 'Title', 'body': 'Body', 'icon': 'icon'}
alert = {'notification': notification, 'message': 'My Message'}
gcm.send(ids, alert)

# Style 2: Notification as keyword argument
notification = {'title': 'Title', 'body': 'Body', 'icon': 'icon'}
gcm.send(ids, 'My Message', notification=notification)
```

For both styles, `notification` must be a `dict`.
