### ISSUE TITLE
APNS not sending Notification to the device nor returning any error in the response.

### ISSUE THREAD

**Issue by dev-gowithdot** [dgilland/pushjack#53]
I am using pushjack 1.6. I had tested the same in January earlier this year but now all of a sudden this is getting me into this weird spot where I dont get any errors in the response and the notification is also not delivered on the device.

Please help it is very urgent.

Thank you in advance and please feel free to request for additional information .

**Comment by dgilland** [comment]
Apple has deprecated the binary APNS API which this library used. I believe they had extended the discontinue date to March 31, 2021 (https://developer.apple.com/news/?id=c88acm2b). So if things have stopped working on your end, then it may be due to this.

You will need to migrate to a different library that supports the new HTTP/2 API. This library is no longer supported/maintained.

**Comment by dev-gowithdot** [comment]
Hi,
Thank you for your response.

Can you suggest any alternative library that we can use?

Thank you

**Comment by dgilland** [comment]
I haven't personally used any of these libraries so I can't personally vouch for them:

- https://github.com/joseph-fox/pushjack (a fork of this project that adds http2 support so might be the easiest transition)
- https://github.com/Pr0Ger/PyAPNs2
- https://github.com/kukosk/pyapns_client

**Comment by dev-gowithdot** [comment]
Thank you so much, I will be trying out these.
